### ISSUE TITLE
table of contents not visible only on the daos doc page

### ISSUE THREAD

**Issue by kaushikvelusamy** [argonne-lcf/user-guides#529]
https://docs.alcf.anl.gov/aurora/data-management/daos/daos-overview/

**Comment by felker** [comment]
Appears normal to me. What do you see? 
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/dba42256-1f2b-4559-928d-d2d0d098db7a">

**Comment by kaushikvelusamy** [comment]
on the right side 
<img width="1525" alt="Screenshot 2024-11-07 at 6 31 44 PM" src="https://github.com/user-attachments/assets/9b30df19-2641-41be-856f-5ed9a4ce5ffc">
<img width="1332" alt="Screenshot 2024-11-07 at 6 31 51 PM" src="https://github.com/user-attachments/assets/398f8b8e-f75b-4c05-8d23-12bd1e95f643">

**Comment by felker** [comment]
I believe the issue is the heading level 1 in
https://github.com/argonne-lcf/user-guides/blob/48f2566540a1469db79ed05edefa1931d5fc80a3/docs/aurora/data-management/daos/daos-overview.md?plain=1#L13

Since there should only be 1x h1 `#`, https://github.com/argonne-lcf/user-guides/blob/48f2566540a1469db79ed05edefa1931d5fc80a3/docs/aurora/data-management/daos/daos-overview.md?plain=1#L1

Fixing now
